from bancoDados.banco_dados import BancoDados
from login.looogin import TelaLogin
if __name__ == "__main__":
    bd = BancoDados()
    tl = TelaLogin(bd)
    tl.iniciar()


# ARRUMAR AS COLUNAS DA TABELA DESPESA_USUÁRIO NO BANCO DE DADOS
# FAZER UMA LISTA COM TUDO (PAGAMENTOS E RECEITAS) PAGAMENTOS VERMELHO E RECEITA VERDE
# FAZER A LISTA DE PAGAMENTOS FUTUROS MOSTRANDO QUAL O PAGAMENTO E QUANDO QUE AS PARCELAS DAQUELE PAGAMENTO VENCEM (ESTILO TABELA)
# FAZER BOTAO PERFIL ONDE O USUÁRIO PODE TROCAR DE SENHA, TROCAR DE E-MAIL E TROCA NOME DE USUÁRIO
# NA TELA PRINCIPAL FAZER BEM VINDO (NOME DO USUÁRIO)
# FAZER COM QUE AO CADASTRAR UM REGISTRO ELE ATUALIZE NOS DADOS
# FAZER COM QUE OS PAGAMENTOS VIGENTE SÓ CONTEMPLEM UMA PARCELA, E QUE SEJA RECONHEÇA AS VIGENTES PELO MES EM QUE FOI CADASTRADO
# FAZER UM BOTÃO INVESTIMENTOS ONDE MOSTRAR TODO O DINHEIRO INVESTIDO, ELE NÃO CONTARÁ NO VALOR DA RECEITA
# REVER TABELA DE DESPESAS, SINTO QUE FALTA ALGO
# NO GRÁFICO MOSTRAR QUAIS OS MAIORES GASTOS BASEADOS NO TIPO DE PAGAMENTO
# NO COMEÇO TENHA ALGUMA COISA NO FRAME, TALVEZ INICIAR COM O PAINEL PRINCIPAL
